source/Facel.Mvc/Controllers/SucursalController.cs
using Facel.Business.Entities;
using Facel.Business.Logics;
using Facel.Filter.Entities;
using Facel.Filter.Logics;
using Facel.Mvc.WebClient.Helpers;
using Marvin.JsonPatch;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Facel.Mvc.Controllers
{
    public class SucursalController : Controller
    {
        public async Task<ActionResult> Index()
        {
            try
            {
                var client = MvcHttpClient.GetClient();

                var response = await client.GetAsync("api/sucursal");

                if (response.IsSuccessStatusCode)
                {
                    string content = await response.Content.ReadAsStringAsync();

                    var list = JsonConvert.DeserializeObject<IEnumerable<Sucursal_BE>>(content);

                    return View(list);
                }
                else
                {
                    return Content("An error occurred");
                }
            }
            catch (Exception ex)
            {
                return Content("An error occurred");
            }
        }

        public ActionResult Create(int? IdEmpresa)
        {
            return View(new Sucursal_BE() { IdEmpresa = IdEmpresa });
        }

        [HttpPost]
        public async Task<ActionResult> Create(Sucursal_BE parambe)
        {
            try
            {
                var client = MvcHttpClient.GetClient();

                var serialized = JsonConvert.SerializeObject(parambe);

                var response = await client.PostAsync("api/sucursal", new StringContent(serialized, System.Text.Encoding.Unicode, "application/json"));

                if (response.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Details", "Sucursal", new { id = parambe.Id });
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred");
                }
            }
            catch (Exception ex)
            {
                return Content("An error occurred");
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var client = MvcHttpClient.GetClient();

                HttpResponseMessage response = await client.GetAsync("api/sucursal/" + id);

                string content = await response.Content.ReadAsStringAsync();

                if (response.IsSuccessStatusCode)
                {
                    var model = JsonConvert.DeserializeObject<Sucursal_BE>(content);
                    return View(model);
                }

                return Content("An error occurred: " + content);
            }
            catch (Exception ex)
            {
                return Content("An error occurred");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(int id, Sucursal_BE parambe)
        {
            try
            {
                var client = MvcHttpClient.GetClient();

                var serialized = JsonConvert.SerializeObject(parambe);

                var response = await client.PutAsync("api/sucursal/" + id, new StringContent(serialized, System.Text.Encoding.Unicode, "application/json"));

                if (response.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Details", "Sucursal", new { id = parambe.Id });
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred");
                }
            }
            catch (Exception ex)
            {
                return Content("An error occurred");
            }
        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var client = MvcHttpClient.GetClient();

                var response = await client.DeleteAsync("api/sucursal/" + id);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("An error occurred");
                }
            }
            catch (Exception ex)
            {
                return Content("An error occurred");
            }
        }
    }
}

source/Facel.Mvc/Views/Sucursal/Create.cshtml
@model Facel.Business.Entities.Sucursal_BE

@{
    ViewBag.Title = "Create";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-3.1.1.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>  
<script type="text/javascript">
    $(document).ready(function () {
        $("input#IdEmpresa").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "http://localhost:11015/api/empresa",
                    type: "GET",
                    dataType: "json",
                    data: { search: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.razonSocial, value: item.razonSocial };
                        }))

                    }
                })
            },
            messages: {
                noResults: "nor", results: "r"
            }
        });
    })
</script>  


<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sucursal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <dl class="dl-horizontal">
            <dt>
                Empresa
            </dt>

            <dd>
                @if (Model.IdEmpresa == null)
                {
                    @Html.EditorFor(model => model.IdEmpresa)
                }
                else
                {
                    @Html.HiddenFor(model => model.IdEmpresa)
                    @Html.DisplayFor(model => model.Empresa.RazonSocial)
                }
            </dd>

        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ubigeo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ubigeo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ubigeo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EsPrincipal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EsPrincipal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EsPrincipal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/Facel.Mvc/Views/Sucursal/Edit.cshtml
@model Facel.Business.Entities.Sucursal_BE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sucursal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Loaded)
        @Html.HiddenFor(model => model.IdEmpresa)
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Empresa.RazonSocial)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Empresa.RazonSocial)
            </dd>

        </dl>
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Ubigeo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ubigeo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ubigeo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Activo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EsPrincipal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EsPrincipal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EsPrincipal, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/Facel.Mvc/Views/Sucursal/Index.cshtml
@model IEnumerable<Facel.Business.Entities.Sucursal_BE>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Sucursal")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ubigeo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EsPrincipal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Empresa.RazonSocial)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ubigeo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EsPrincipal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Empresa.RazonSocial)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>